### ISSUE TITLE
deb_src does not work as advertised

### ISSUE THREAD

**Issue by mheffner** [cookbooks/apt#1]
The readme says:

`deb_src: whether or not to add the repository as a source repo as well`

So, when setting "deb_src true", I would assume this adds deb-src _as well_ as the deb entry. Instead, however, it switches to only adding the deb-src entry.

Not sure if the readme or the code is wrong, but these don't match.

**Comment by hedgehog** [comment]
I'm happy to accept either correction.  Pull requests against the `qa` branch please.

**Comment by sometimesfood** [comment]
Here's a pull request: https://github.com/cookbooks/apt/pull/3

**Comment by hedgehog** [comment]
@mheffner, could you review @sometimesfood pull request #4 (above) and confirm that it fixes this issue for you.  Whenyou ack, I'll pull it into the `qa` branch.  Thanks

**Comment by mheffner** [comment]
Looks like this was merged already, but I just tested this and it works for me. :thumbsup:

**Comment by hedgehog** [comment]
@mheffner, yup I probbaly mixed up your response on another issue will take more care, and hopefully as/when the cookbooks teams start to grow incidents like this will be less likely.  Again apologies, didn't mean to waste your time :)
