### ISSUE TITLE
handle google-chrome repos

### ISSUE THREAD

**Issue by hedgehog** [cookbooks/apt#5]
As best I can work out the apt LWRP cannot handle the google-chrome ppa:
http://www.ubuntuupdates.org/ppas/8

```
apt_repository "google-chrome-stable" do
  uri "http://dl.google.com/linux/chrome/"
  #distribution 'deb' #node['lsb']['codename']
  components ["main", "stable"]
  key "https://dl-ssl.google.com/linux/linux_signing_key.pub"
  action :add
end
```

Yields

```
Err http://dl.google.com lucid/stable Packages
  404  Not Found
Err http://archive.canonical.com lucid Release.gpg
  Could not connect to archive.canonical.com:80 (91.189.88.33). - connect (110: Connection timed out)
Ign http://archive.canonical.com lucid Release
Ign http://archive.canonical.com lucid/partner Packages
Ign http://archive.canonical.com lucid/partner Packages
Err http://archive.canonical.com lucid/partner Packages
  Unable to connect to archive.canonical.com:http:
Fetched 13.8kB in 21s (656B/s)
STDERR: W: Failed to fetch http://archive.canonical.com/dists/lucid/Release.gpg  Could not connect to archive.canonical.com:80 (91.189.88.33). - connect (110: Connection timed out)

W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/lucid/main/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/lucid/stable/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://archive.canonical.com/dists/lucid/partner/binary-amd64/Packages.gz  Unable to connect to archive.canonical.com:http:

E: Some index files failed to download, they have been ignored, or old ones used instead.
---- End output of apt-get update ----
```

**Comment by sometimesfood** [comment]
That's because you mixed up distribution and components and used an incomplete URL.

Try this instead:

``` ruby
apt_repository 'google-chrome-stable' do
  uri 'http://dl.google.com/linux/chrome/deb/'
  distribution 'stable'
  components ['main']
  key 'https://dl-ssl.google.com/linux/linux_signing_key.pub'
  action :add
end
```

**Comment by sometimesfood** [comment]
Btw, maybe you want to retrieve the signing key from a GPG Keyserver instead:

``` ruby
apt_repository 'google-chrome-stable' do
  uri 'http://dl.google.com/linux/chrome/deb/'
  distribution 'stable'
  components ['main']
  keyserver 'keys.gnupg.net'
  key '7FAC5991'
  action :add
end
```

**Comment by hedgehog** [comment]
Yup, the above was just the last permutation I tried.  With the snippet you suggest, which I had tried previously I get:

```
Ign http://dl.google.com lucid/stable Packages
Err http://dl.google.com lucid/main Packages
  404  Not Found
Err http://dl.google.com lucid/stable Packages
  404  Not Found
Fetched 14.0kB in 11s (1190B/s)
STDERR: W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/lucid/main/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/lucid/stable/binary-amd64/Packages.gz  404  Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.
---- End output of apt-get update ----
Ran apt-get update returned 100
: stdout
The following SSH command responded with a non-zero exit status.
```

**Comment by hedgehog** [comment]
Changing the key source, changes the error, but still shows a failure:

```
Ign http://dl.google.com lucid/main Packages
Hit http://ppa.launchpad.net lucid/main Packages
Hit http://us.archive.ubuntu.com lucid-updates/multiverse Sources
Ign http://dl.google.com lucid/stable Packages
Hit http://ppa.launchpad.net lucid/main Packages
Hit http://ppa.launchpad.net lucid/main Packages
Hit http://ppa.launchpad.net lucid/main Packages
Err http://dl.google.com lucid/main Packages
  404  Not Found
Hit http://security.ubuntu.com lucid-security/multiverse Sources
Err http://dl.google.com lucid/stable Packages
  404  Not Found
Fetched 13.8kB in 4s (3357B/s)
STDERR: W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/lucid/main/binary-amd64/Packages.gz  404  Not Found

W: Failed to fetch http://dl.google.com/linux/chrome/deb/dists/lucid/stable/binary-amd64/Packages.gz  404  Not Found

E: Some index files failed to download, they have been ignored, or old ones used instead.
---- End output of apt-get update ----
Ran apt-get update returned 100
: stdout
```

**Comment by sometimesfood** [comment]
Could you copy and paste your last attempt? Both of the examples that I posted work just fine here.

**Comment by hedgehog** [comment]
Yup, I'm beginning to think there is something stale leftover from a chef run.
Last attempt was this:

```
apt_repository 'google-chrome-stable' do
  uri 'http://dl.google.com/linux/chrome/deb/'
  distribution 'stable'
  components ['main']
  keyserver 'keys.gnupg.net'
  key '7FAC5991'
  action :add
end
```

**Comment by sometimesfood** [comment]
Oh, that's another bug of the apt cookbook that I wanted to report. You can't edit repos, [you can only add them with the apt cookbook](https://github.com/cookbooks/apt/blob/fd5c796e3c5d6adc6af69767ed4e30c33ebfd37c/providers/repository.rb#L21).

Unfortunately the fix isn't quite as trivial as removing this line, we need a check for retrieved keys first. I'll file a proper bug report later today.

Try something like this (just for testing):

``` ruby
apt_repository 'google-chrome-stable' do
  action :remove
end

apt_repository 'google-chrome-stable' do
  uri 'http://dl.google.com/linux/chrome/deb/'
  distribution 'stable'
  components ['main']
  keyserver 'keys.gnupg.net'
  key '7FAC5991'
  action :add
end
```

**Comment by hedgehog** [comment]
Ah Ha.  That should probably also go in the readme :)  So essentially I never escaped my first wrong value that distribution set to - makes sense now - thought I was quietly going mad. Will try your suggestion.

**Comment by sometimesfood** [comment]
It would probably be a better idea to just fix this behaviour instead
of documenting it. I'll open an issue and look into it.

**Comment by hedgehog** [comment]
OKay, given Chef's typical behavior - if something goes wrong your worst case should be to just rerun the `chef-client`/`chef-solo` - maybe the correct behavior is to automagically do a `:remove` before every `:add`?

**Comment by sometimesfood** [comment]
No, that would trigger _a lot_ of `apt-get update`s and key fetches.

I think we should
- only fetch keyrings if they are not yet present (otherwise the key ring is fetched at each chef run)
- remove the `unless File.exists` seen [here](https://github.com/cookbooks/apt/blob/fd5c796e3c5d6adc6af69767ed4e30c33ebfd37c/providers/repository.rb#L21)

The check for existing keyrings is not quite as easy as it sounds, though.

Keys can be fetched via HTTP before being added by `apt-key`, in which case a check could become rather tedious. It would probably be a good idea to put keys into `/etc/apt/trusted.gpg.d`. Having one file per key is more maintainable anyway.

**Comment by hedgehog** [comment]
Good points.  My specialty lies elsewhere so I'll leave this to you :)
The maillist might have opinions - up to you. 

Hopefully you are now able to merge pull requests and push directly your self, though it might be a useful audit mechanism to make your commits via pull requests - again for you to decide.

Thanks again for volunteering.

**Comment by hedgehog** [comment]
Closing this since @sometimesfood will be opening a overwrite feature request.

**Comment by sometimesfood** [comment]
See gh-8 for the overwrite feature request.

/cc @hedgehog
